name: "Pull request"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop, main]

jobs:
  PR:
    uses: "Siigo-SREDevops/components/.github/workflows/secops-secrets-scanner.yml@master"
    secrets: inherit